/**
 * Port of the exporter's per-frame camera path — the INLINE pre-pass inside
 * `VideoExporter.export` (Services/VideoExporter.swift lines 410–614 at
 * da569841c7b63175bffa46d897457f157224774d: the spring state vars,
 * `tiltSpringTarget`, `tiltRegionTarget`, `combinedTiltKey` and the
 * `cameraPath` map) plus `private struct CameraKey` (line 3922).
 *
 * This is what the Mac EXPORT renders frame by frame, so it is what the web
 * export (and the parity gate) must render: one `CameraKey` per output frame.
 * It differs from the preview's PreviewMotionModel on purpose (no substeps,
 * snap only for dt ≤ 0 or dt > 0.35 s, the card offset is NOT snapped).
 *
 * Locked to Swift by the `exportCameraPath` golden vectors, generated by the
 * verbatim oracle `WebCameraPathOracle.cameraPath` (WebVectors+CameraMotionOracle.swift),
 * which the coordinator cross-checks against the REAL exporter's
 * `CAPTURECAT_DUMP_CAMERA=1` dump in `--web-parity-fixtures`.
 *
 * Inputs (all SOURCE seconds except `outputFrameTimes`):
 * - `outputFrameTimes`: the exporter's `exportFrameTimes(...)` in seconds
 *   (`CMTime(seconds: i/fps, preferredTimescale: 600).seconds`).
 * - `timelineSourceTimes`: `timeMap.sourceTime(forOutput:)` of each frame.
 * - `cursorEvents`: the exporter's processed events (menu-bar-crop shifted).
 * - `displayWidth/Height`: the resolved (crop-scaled) cursor coordinate size.
 * - `scrollTimes`: sorted scroll-tick timestamps from keys.json.
 *
 * Faithful-port oddities (reported, not fixed — the port must match Swift):
 * - The snap branch (dt ≤ 0 or dt > 0.35) snaps zoom/focal/tilt but leaves
 *   the card offset AND its velocity untouched, so the offset keeps its
 *   pre-jump value/velocity into the next integrated frame.
 * - The springs are semi-implicit Euler with ONE step per output frame
 *   (PreviewMotionModel substeps to ≤ 1/60 s). That is unstable once
 *   ω·dt ≳ 1/ζ: e.g. an Instant block (ω = 20/animDur) at Quick/Rapid speed,
 *   Instant at Mellow + 24 fps, or ANY style inside a 4–8× speed region at
 *   30 fps (source dt up to 0.35 s) — the zoom/offset/tilt diverge
 *   (zoom → 1e+50, clamped only at the 0.25 floor) while the preview stays
 *   sane. The golden vectors contain such diverging paths on purpose.
 */
import type { CursorEvent, Point, ProjectSettings, TiltRegion, ZoomRegion } from "../model/types";
import { animationSpeedDuration } from "../model/enums";
import { interpolateIfFresh } from "./cursorSmoother";
import { smax, smin } from "./swift";
import { introAmount, makeTiltStyleMemory, rampOutScale, tiltReturnParams } from "./tiltMath";
import {
  blendedFocalPoint,
  makeRegionMemory,
  regionTargets,
  restLandingBand,
  settleTowardRest,
  settleTowardZero,
} from "./zoomFocalMath";

/** `VideoExporter.CameraKey` — one frame's camera. Offsets are canvas
 * fractions, Y-down; tilt angles are the FINAL combined degrees (settings
 * mode skew × amount + timeline tilt-region springs). */
export interface CameraKey {
  zoom: number;
  focalX: number;
  focalY: number;
  offsetX: number;
  offsetY: number;
  tiltPitch: number;
  tiltYaw: number;
  tiltRoll: number;
}

export type CameraPathSettings = Pick<
  ProjectSettings,
  | "animationSpeed"
  | "screenTiltMode"
  | "screenTiltAngle"
  | "screenTiltYaw"
  | "screenTiltRoll"
  | "cameraFollowSpeed"
>;

export interface CameraPathInput {
  zoomRegions: readonly ZoomRegion[];
  tiltRegions: readonly TiltRegion[];
  settings: CameraPathSettings;
  outputFrameTimes: readonly number[];
  timelineSourceTimes: readonly number[];
  cursorEvents: readonly CursorEvent[];
  displayWidth: number;
  displayHeight: number;
  scrollTimes: readonly number[];
}

/** The exporter's `cameraPath`: one CameraKey per entry of
 * `timelineSourceTimes` (indexing `outputFrameTimes` by the same frame index). */
export function computeCameraPath(input: CameraPathInput): CameraKey[] {
  const { zoomRegions, tiltRegions, settings, outputFrameTimes, timelineSourceTimes, cursorEvents } = input;
  const { displayWidth, displayHeight, scrollTimes } = input;

  const animDur = smax(0.2, animationSpeedDuration(settings.animationSpeed));
  let springZoom = 1.0;
  let springZoomVel = 0.0;
  let springOffsetX = 0.0;
  let springOffsetVelX = 0.0;
  let springOffsetY = 0.0;
  let springOffsetVelY = 0.0;
  let springFocalX = 0.5;
  let springFocalY = 0.5;
  const springRegionMemory = makeRegionMemory();
  let springFocalVelX = 0.0;
  let springFocalVelY = 0.0;
  let lastSpringTime: number | null = null;

  const tiltMode = settings.screenTiltMode;
  const tiltPitch = settings.screenTiltAngle;
  const tiltYaw = settings.screenTiltYaw;
  const tiltRoll = settings.screenTiltRoll;
  let springTilt = 0.0;
  let springTiltVel = 0.0;
  let springRegionPitch = 0.0;
  let springRegionPitchVel = 0.0;
  const springTiltStyleMemory = makeTiltStyleMemory();
  let springRegionYaw = 0.0;
  let springRegionYawVel = 0.0;
  let springRegionRoll = 0.0;
  let springRegionRollVel = 0.0;

  function tiltSpringTarget(targetZoom: number): number {
    if (!(tiltMode === "Zoomed Out" || tiltMode === "Both")) return 0;
    return targetZoom > 1.0 ? 0 : 1;
  }
  function tiltRegionTarget(t: number): { pitch: number; yaw: number; roll: number } {
    for (const region of tiltRegions) {
      if (t >= region.startTime && t <= region.endTime) {
        const scale = rampOutScale(t, region.startTime, region.endTime, animDur);
        return { pitch: region.pitch * scale, yaw: region.yaw * scale, roll: region.roll * scale };
      }
    }
    return { pitch: 0, yaw: 0, roll: 0 };
  }
  function combinedTiltKey(zoom: number, focalX: number, focalY: number, outputTime: number): CameraKey {
    let amount = tiltMode === "Zoomed Out" || tiltMode === "Both" ? springTilt : 0;
    if (tiltMode === "Intro" || tiltMode === "Both") {
      amount = smax(amount, introAmount(outputTime, animDur));
    }
    amount = smax(0, smin(1, amount));
    return {
      zoom,
      focalX,
      focalY,
      offsetX: springOffsetX,
      offsetY: springOffsetY,
      tiltPitch: amount * tiltPitch + springRegionPitch,
      tiltYaw: amount * tiltYaw + springRegionYaw,
      tiltRoll: amount * tiltRoll + springRegionRoll,
    };
  }

  const path: CameraKey[] = new Array(timelineSourceTimes.length);
  for (let frameIdx = 0; frameIdx < timelineSourceTimes.length; frameIdx++) {
    const t = timelineSourceTimes[frameIdx];

    const targets = regionTargets(zoomRegions, t, springZoom, animDur, springRegionMemory);
    const targetZoom = targets.zoom;

    let scrolling = false;
    if (scrollTimes.length !== 0) {
      let lo = 0;
      let hi = scrollTimes.length - 1;
      while (lo < hi) {
        const mid = Math.floor((lo + hi) / 2);
        if (scrollTimes[mid] < t) lo = mid + 1;
        else hi = mid;
      }
      let best = Math.abs(scrollTimes[lo] - t);
      if (lo > 0) best = smin(best, Math.abs(scrollTimes[lo - 1] - t));
      scrolling = best < 0.35;
    }
    const cursorPos: Point | null =
      scrolling || cursorEvents.length === 0 ? null : interpolateIfFresh(cursorEvents, t);
    const focalTarget = blendedFocalPoint(
      targets.focal,
      cursorPos,
      displayWidth,
      displayHeight,
      springZoom,
      targets.envelope,
      targets.cursorFollow,
    );

    const lastTime = lastSpringTime;
    if (lastTime === null) {
      springZoom = targetZoom;
      springOffsetX = targets.offset.x;
      springOffsetY = targets.offset.y;
      springFocalX = focalTarget.x;
      springFocalY = focalTarget.y;
      springTilt = tiltSpringTarget(targetZoom);
      const regionTarget = tiltRegionTarget(t);
      springRegionPitch = regionTarget.pitch;
      springRegionYaw = regionTarget.yaw;
      springRegionRoll = regionTarget.roll;
      lastSpringTime = t;
      path[frameIdx] = combinedTiltKey(springZoom, springFocalX, springFocalY, outputFrameTimes[frameIdx]);
      continue;
    }

    const dt = t - lastTime;
    lastSpringTime = t;

    if (dt > 0 && dt <= 0.35) {
      // Zoom spring
      const zOmega = (2.5 / animDur) * targets.omegaMultiplier;
      const zZeta = targets.damping;
      const zAcc = zOmega * zOmega * (targetZoom - springZoom) - 2 * zZeta * zOmega * springZoomVel;
      springZoomVel += zAcc * dt;
      springZoom = smax(0.25, springZoom + springZoomVel * dt);
      if (targetZoom === 1 && Math.abs(springZoom - 1) < restLandingBand) {
        const r = settleTowardRest(springZoom, springZoomVel, dt);
        springZoom = r.zoom;
        springZoomVel = r.velocity;
      }

      // Card offset — same spring as the zoom
      const oxAcc = zOmega * zOmega * (targets.offset.x - springOffsetX) - 2 * zZeta * zOmega * springOffsetVelX;
      const oyAcc = zOmega * zOmega * (targets.offset.y - springOffsetY) - 2 * zZeta * zOmega * springOffsetVelY;
      springOffsetVelX += oxAcc * dt;
      springOffsetVelY += oyAcc * dt;
      springOffsetX += springOffsetVelX * dt;
      springOffsetY += springOffsetVelY * dt;

      // Focal spring
      const fOmega = 5.5 * (0.4 + 1.2 * smax(0, smin(1, settings.cameraFollowSpeed)));
      const fZeta = 0.9;
      const fxAcc = fOmega * fOmega * (focalTarget.x - springFocalX) - 2 * fZeta * fOmega * springFocalVelX;
      const fyAcc = fOmega * fOmega * (focalTarget.y - springFocalY) - 2 * fZeta * fOmega * springFocalVelY;
      springFocalVelX += fxAcc * dt;
      springFocalVelY += fyAcc * dt;
      springFocalX = smax(0, smin(1, springFocalX + springFocalVelX * dt));
      springFocalY = smax(0, smin(1, springFocalY + springFocalVelY * dt));

      // Tilt springs
      const tiltTarget = tiltSpringTarget(targetZoom);
      const tAcc = zOmega * zOmega * (tiltTarget - springTilt) - 2 * zZeta * zOmega * springTiltVel;
      springTiltVel += tAcc * dt;
      springTilt += springTiltVel * dt;

      const regionTarget = tiltRegionTarget(t);
      const tiltParams = tiltReturnParams(tiltRegions, t, animDur, springTiltStyleMemory);
      const tiltReturning = tiltParams.returning;
      const rOmegaMult = tiltParams.omega;
      const rZeta = tiltParams.damping;
      const rOmega = (2.5 / animDur) * rOmegaMult;
      {
        const acc = rOmega * rOmega * (regionTarget.pitch - springRegionPitch) - 2 * rZeta * rOmega * springRegionPitchVel;
        springRegionPitchVel += acc * dt;
        springRegionPitch += springRegionPitchVel * dt;
      }
      {
        const acc = rOmega * rOmega * (regionTarget.yaw - springRegionYaw) - 2 * rZeta * rOmega * springRegionYawVel;
        springRegionYawVel += acc * dt;
        springRegionYaw += springRegionYawVel * dt;
      }
      {
        const acc = rOmega * rOmega * (regionTarget.roll - springRegionRoll) - 2 * rZeta * rOmega * springRegionRollVel;
        springRegionRollVel += acc * dt;
        springRegionRoll += springRegionRollVel * dt;
      }
      if (tiltReturning) {
        let s = settleTowardZero(springRegionPitch, springRegionPitchVel, dt, 1.5);
        springRegionPitch = s.value;
        springRegionPitchVel = s.velocity;
        s = settleTowardZero(springRegionYaw, springRegionYawVel, dt, 1.5);
        springRegionYaw = s.value;
        springRegionYawVel = s.velocity;
        s = settleTowardZero(springRegionRoll, springRegionRollVel, dt, 1.5);
        springRegionRoll = s.value;
        springRegionRollVel = s.velocity;
      }
    } else {
      // Large jump (trimmed segment boundary): snap — card offset untouched.
      springZoom = targetZoom;
      springZoomVel = 0;
      springFocalX = focalTarget.x;
      springFocalVelX = 0;
      springFocalY = focalTarget.y;
      springFocalVelY = 0;
      springTilt = tiltSpringTarget(targetZoom);
      springTiltVel = 0;
      const regionTarget = tiltRegionTarget(t);
      springRegionPitch = regionTarget.pitch;
      springRegionPitchVel = 0;
      springRegionYaw = regionTarget.yaw;
      springRegionYawVel = 0;
      springRegionRoll = regionTarget.roll;
      springRegionRollVel = 0;
    }

    path[frameIdx] = combinedTiltKey(springZoom, springFocalX, springFocalY, outputFrameTimes[frameIdx]);
  }
  return path;
}
