-- Better Auth 1.6.25 core schema + @better-auth/stripe subscription table
-- + the desktop loopback/PKCE authorization-code exchange table.
--
-- The five Better Auth tables and their three indexes below are the VERBATIM
-- output of Better Auth's own migration compiler. They were generated by
-- running, against this repo's installed packages:
--
--   const { compileMigrations } = await getMigrations(auth.options);
--   console.log(await compileMigrations());
--
-- with exactly the plugin set from src/lib/auth.ts — bearer(), oneTimeToken()
-- and @better-auth/stripe with subscription.enabled — and the
-- user.additionalFields { tester, blocked }. Only formatting (whitespace,
-- casing of keywords, comments) has been changed; column names, types,
-- ordering and constraints are untouched.
--
-- DO NOT hand-edit the column names or types. The Kysely adapter runs with
-- casing "camel", so columns are camelCase and must be quoted. `date` columns
-- hold ISO-8601 TEXT and `integer` columns hold 0/1 — the sqlite adapter runs
-- with supportsDates:false, so no Date object is ever bound, which matters
-- because D1's .bind() rejects objects.
--
-- If Better Auth is upgraded and adds columns, regenerate with
-- `npx @better-auth/cli generate` and add a NEW numbered migration. wrangler's
-- numbered migrations stay the single source of truth for this repo; do not
-- use Better Auth's runtime getMigrations()/runMigrations() endpoint here.

CREATE TABLE IF NOT EXISTS "user" (
  "id"               text    NOT NULL PRIMARY KEY,
  "name"             text    NOT NULL,
  "email"            text    NOT NULL UNIQUE,
  "emailVerified"    integer NOT NULL,
  "image"            text,
  "createdAt"        date    NOT NULL,
  "updatedAt"        date    NOT NULL,
  "stripeCustomerId" text,              -- added by @better-auth/stripe
  "tester"           integer,           -- user.additionalFields, input:false
  "blocked"          integer            -- user.additionalFields, input:false
);

-- "token" is the value the desktop app stores in the Keychain and sends as
-- `Authorization: Bearer <token>`.
CREATE TABLE IF NOT EXISTS "session" (
  "id"        text NOT NULL PRIMARY KEY,
  "expiresAt" date NOT NULL,
  "token"     text NOT NULL UNIQUE,
  "createdAt" date NOT NULL,
  "updatedAt" date NOT NULL,
  "ipAddress" text,
  "userAgent" text,
  "userId"    text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "account" (
  "id"                    text NOT NULL PRIMARY KEY,
  "accountId"             text NOT NULL,
  "providerId"            text NOT NULL,
  "userId"                text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
  "accessToken"           text,
  "refreshToken"          text,
  "idToken"               text,
  "accessTokenExpiresAt"  date,
  "refreshTokenExpiresAt" date,
  "scope"                 text,
  "password"              text,
  "createdAt"             date NOT NULL,
  "updatedAt"             date NOT NULL
);

-- Also backs the oneTimeToken plugin (identifier = "one-time-token:<sha256>")
-- and the OAuth state store (identifier = the 32-char state value).
CREATE TABLE IF NOT EXISTS "verification" (
  "id"         text NOT NULL PRIMARY KEY,
  "identifier" text NOT NULL,
  "value"      text NOT NULL,
  "expiresAt"  date NOT NULL,
  "createdAt"  date NOT NULL,
  "updatedAt"  date NOT NULL
);

-- Written ONLY by @better-auth/stripe's webhook handler. "status" holds the
-- raw Stripe status verbatim; "referenceId" = user.id and is deliberately NOT
-- unique (cancel + resubscribe yields a second row), so entitlement checks are
-- existence checks rather than single-row status reads.
CREATE TABLE IF NOT EXISTS "subscription" (
  "id"                   text NOT NULL PRIMARY KEY,
  "plan"                 text NOT NULL,
  "referenceId"          text NOT NULL,
  "stripeCustomerId"     text,
  "stripeSubscriptionId" text,
  "status"               text NOT NULL,
  "periodStart"          date,
  "periodEnd"            date,
  "trialStart"           date,
  "trialEnd"             date,
  "cancelAtPeriodEnd"    integer,
  "cancelAt"             date,
  "canceledAt"           date,
  "endedAt"              date,
  "seats"                integer,
  "billingInterval"      text,
  "stripeScheduleId"     text
);

-- Better Auth's own indexes (verbatim from compileMigrations).
CREATE INDEX IF NOT EXISTS "session_userId_idx"          ON "session" ("userId");
CREATE INDEX IF NOT EXISTS "account_userId_idx"          ON "account" ("userId");
CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" ("identifier");

-- Ours. The entitlement hot path is
--   SELECT 1 FROM subscription WHERE referenceId = ? AND status IN (...)
-- on every authenticated request, and the Stripe plugin does findMany on
-- stripeCustomerId inside its webhook handlers.
CREATE INDEX IF NOT EXISTS "subscription_referenceId_idx"      ON "subscription" ("referenceId");
CREATE INDEX IF NOT EXISTS "subscription_stripeCustomerId_idx" ON "subscription" ("stripeCustomerId");
CREATE INDEX IF NOT EXISTS "user_stripeCustomerId_idx"         ON "user" ("stripeCustomerId");

-- ---------------------------------------------------------------------------
-- Desktop loopback + PKCE authorization-code exchange (RFC 8252 / RFC 7636).
--
-- Better Auth has no plugin that binds PKCE to a loopback redirect with a
-- RANDOM port: the oauthProvider plugin matches redirect URIs by exact string
-- equality, and RFC 8252 §7.3 requires accepting any port on loopback, which
-- therefore cannot be pre-registered. So this table is ours.
--
-- It stores ONLY the code_challenge and the redirect_uri. The "code" handed to
-- the loopback listener is a Better Auth one-time token, so its 2-minute TTL
-- and single-use semantics are enforced by the `verification` table above;
-- `consumed` here is the second, independent burn.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS desktop_auth_requests (
  id             TEXT PRIMARY KEY,            -- rid, uuid v4
  code_challenge TEXT NOT NULL,               -- base64url(SHA256(verifier)), S256 only
  redirect_uri   TEXT NOT NULL,               -- validated loopback URI incl. the random port
  client_state   TEXT,                        -- opaque, echoed back to the app
  provider       TEXT NOT NULL,               -- 'apple' | 'google'
  ott_hash       TEXT,                        -- base64url(SHA256(one-time token)), set at /complete
  consumed       INTEGER NOT NULL DEFAULT 0,
  created_at     INTEGER NOT NULL,            -- unix seconds
  expires_at     INTEGER NOT NULL             -- unix seconds, created_at + 600
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_desktop_auth_ott    ON desktop_auth_requests (ott_hash);
CREATE INDEX        IF NOT EXISTS idx_desktop_auth_expiry ON desktop_auth_requests (expires_at);
