// Generates apps/web/src/editor/engine/gpu/cameraFilterLuts.ts — the webcam
// filter presets (CameraStyleMath.adjustedImage: CIPhotoEffectMono / Noir /
// Fade, CITemperatureAndTint Warm 6500→5100 K / Cool 6500→8200 K) sampled
// from the REAL CoreImage filters as 17³ colour cubes. Apple implements the
// Photos effects as colour cubes itself; the web samples these with hardware
// trilinear filtering. Measured against a 33³ CoreImage grid: mean ≈ 0.3/255,
// p99 ≤ 2.5/255, max ≤ 6/255 (Fade, extreme saturated corners).
//
// The context's working space is non-linear sRGB — the exporter's
// `renderSpace` for sRGB sources (VideoColorTags.renderColorSpace).
//
//   swift apps/web/scripts/camera-filter-luts.swift > apps/web/src/editor/engine/gpu/cameraFilterLuts.ts
import CoreImage
import Foundation

let n = 17
let srgb = CGColorSpace(name: CGColorSpace.sRGB)!
let ctx = CIContext(options: [.workingColorSpace: srgb, .useSoftwareRenderer: false])

// Grid in CUBE order (r fastest, then g, then b) = WebGPU 3D texture layout (x = r, y = g, z = b).
var bytes = [UInt8](repeating: 255, count: n * n * n * 4)
for b in 0..<n { for g in 0..<n { for r in 0..<n {
    let i = (b * n * n + g * n + r) * 4
    let s = { (v: Int) in UInt8((Double(v) * 255.0 / Double(n - 1)).rounded()) }
    bytes[i] = s(r); bytes[i + 1] = s(g); bytes[i + 2] = s(b)
}}}
let w = n * n, h = n
let input = CIImage(bitmapData: Data(bytes), bytesPerRow: w * 4, size: CGSize(width: w, height: h), format: .RGBA8, colorSpace: srgb)

func cube(_ img: CIImage, grey: Bool) -> String {
    var out = [UInt8](repeating: 0, count: w * h * 4)
    ctx.render(img.cropped(to: input.extent), toBitmap: &out, rowBytes: w * 4, bounds: input.extent, format: .RGBA8, colorSpace: srgb)
    var packed = [UInt8]()
    for i in 0..<(n * n * n) {
        if grey { packed.append(out[i * 4]) } else { packed += [out[i * 4], out[i * 4 + 1], out[i * 4 + 2]] }
    }
    return Data(packed).base64EncodedString()
}

let tt = { (target: Double) in
    input.applyingFilter("CITemperatureAndTint", parameters: [
        "inputNeutral": CIVector(x: 6500, y: 0), "inputTargetNeutral": CIVector(x: target, y: 0),
    ])
}
let entries: [(String, CIImage, Bool)] = [
    ("Mono", input.applyingFilter("CIPhotoEffectMono"), true),
    ("Noir", input.applyingFilter("CIPhotoEffectNoir"), true),
    ("Fade", input.applyingFilter("CIPhotoEffectFade"), false),
    ("Warm", tt(5100), false),
    ("Cool", tt(8200), false),
]
var ts = """
/**
 * GENERATED by apps/web/scripts/camera-filter-luts.swift — do not edit.
 * The webcam filter presets (CameraStyleMath.adjustedImage) sampled from the
 * REAL CoreImage filters (\(ProcessInfo.processInfo.operatingSystemVersionString))
 * as \(n)³ colour cubes in a non-linear sRGB working space (the exporter's).
 * Layout: r fastest, then g, then b; grey cubes store one channel.
 */
export const CAMERA_LUT_SIZE = \(n);

export const CAMERA_FILTER_LUTS: Record<"Mono" | "Noir" | "Fade" | "Warm" | "Cool", { grey: boolean; data: string }> = {

"""
for (name, img, grey) in entries {
    ts += "  \(name): { grey: \(grey), data: \"\(cube(img, grey: grey))\" },\n"
}
ts += "};\n"
print(ts, terminator: "")
