/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AlternativesSlugRouteImport } from './routes/alternatives.$slug'
import { Route as ApiOembedRouteImport } from './routes/api/oembed'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as EmbedVideoIdRouteImport } from './routes/embed.$videoId'
import { Route as MdShareVideoIdRouteImport } from './routes/md-share.$videoId'
import { Route as MdSplatRouteImport } from './routes/md.$'
import { Route as ShareVideoIdRouteImport } from './routes/share.$videoId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as AppVideosVideoIdIndexRouteImport } from './routes/app/videos.$videoId.index'
import { Route as AppVideosVideoIdAnalyticsRouteImport } from './routes/app/videos.$videoId.analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternativesSlugRoute = AlternativesSlugRouteImport.update({
  id: '/alternatives/$slug',
  path: '/alternatives/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOembedRoute = ApiOembedRouteImport.update({
  id: '/api/oembed',
  path: '/api/oembed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedVideoIdRoute = EmbedVideoIdRouteImport.update({
  id: '/embed/$videoId',
  path: '/embed/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const MdShareVideoIdRoute = MdShareVideoIdRouteImport.update({
  id: '/md-share/$videoId',
  path: '/md-share/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const MdSplatRoute = MdSplatRouteImport.update({
  id: '/md/$',
  path: '/md/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareVideoIdRoute = ShareVideoIdRouteImport.update({
  id: '/share/$videoId',
  path: '/share/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideosVideoIdIndexRoute = AppVideosVideoIdIndexRouteImport.update({
  id: '/videos/$videoId/',
  path: '/videos/$videoId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVideosVideoIdAnalyticsRoute =
  AppVideosVideoIdAnalyticsRouteImport.update({
    id: '/videos/$videoId/analytics',
    path: '/videos/$videoId/analytics',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/agents': typeof AgentsRoute
  '/beta': typeof BetaRoute
  '/download': typeof DownloadRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/alternatives/$slug': typeof AlternativesSlugRoute
  '/api/oembed': typeof ApiOembedRoute
  '/app/billing': typeof AppBillingRoute
  '/app/settings': typeof AppSettingsRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/embed/$videoId': typeof EmbedVideoIdRoute
  '/md-share/$videoId': typeof MdShareVideoIdRoute
  '/md/$': typeof MdSplatRoute
  '/share/$videoId': typeof ShareVideoIdRoute
  '/app/': typeof AppIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/videos/$videoId/analytics': typeof AppVideosVideoIdAnalyticsRoute
  '/app/videos/$videoId/': typeof AppVideosVideoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/agents': typeof AgentsRoute
  '/beta': typeof BetaRoute
  '/download': typeof DownloadRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/alternatives/$slug': typeof AlternativesSlugRoute
  '/api/oembed': typeof ApiOembedRoute
  '/app/billing': typeof AppBillingRoute
  '/app/settings': typeof AppSettingsRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/embed/$videoId': typeof EmbedVideoIdRoute
  '/md-share/$videoId': typeof MdShareVideoIdRoute
  '/md/$': typeof MdSplatRoute
  '/share/$videoId': typeof ShareVideoIdRoute
  '/app': typeof AppIndexRoute
  '/compare': typeof CompareIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/videos/$videoId/analytics': typeof AppVideosVideoIdAnalyticsRoute
  '/app/videos/$videoId': typeof AppVideosVideoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/agents': typeof AgentsRoute
  '/beta': typeof BetaRoute
  '/download': typeof DownloadRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/alternatives/$slug': typeof AlternativesSlugRoute
  '/api/oembed': typeof ApiOembedRoute
  '/app/billing': typeof AppBillingRoute
  '/app/settings': typeof AppSettingsRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/embed/$videoId': typeof EmbedVideoIdRoute
  '/md-share/$videoId': typeof MdShareVideoIdRoute
  '/md/$': typeof MdSplatRoute
  '/share/$videoId': typeof ShareVideoIdRoute
  '/app/': typeof AppIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/videos/$videoId/analytics': typeof AppVideosVideoIdAnalyticsRoute
  '/app/videos/$videoId/': typeof AppVideosVideoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/$username'
    | '/agents'
    | '/beta'
    | '/download'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/alternatives/$slug'
    | '/api/oembed'
    | '/app/billing'
    | '/app/settings'
    | '/compare/$slug'
    | '/embed/$videoId'
    | '/md-share/$videoId'
    | '/md/$'
    | '/share/$videoId'
    | '/app/'
    | '/compare/'
    | '/api/trpc/$'
    | '/app/videos/$videoId/analytics'
    | '/app/videos/$videoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/agents'
    | '/beta'
    | '/download'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/alternatives/$slug'
    | '/api/oembed'
    | '/app/billing'
    | '/app/settings'
    | '/compare/$slug'
    | '/embed/$videoId'
    | '/md-share/$videoId'
    | '/md/$'
    | '/share/$videoId'
    | '/app'
    | '/compare'
    | '/api/trpc/$'
    | '/app/videos/$videoId/analytics'
    | '/app/videos/$videoId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/$username'
    | '/agents'
    | '/beta'
    | '/download'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/alternatives/$slug'
    | '/api/oembed'
    | '/app/billing'
    | '/app/settings'
    | '/compare/$slug'
    | '/embed/$videoId'
    | '/md-share/$videoId'
    | '/md/$'
    | '/share/$videoId'
    | '/app/'
    | '/compare/'
    | '/api/trpc/$'
    | '/app/videos/$videoId/analytics'
    | '/app/videos/$videoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  UsernameRoute: typeof UsernameRoute
  AgentsRoute: typeof AgentsRoute
  BetaRoute: typeof BetaRoute
  DownloadRoute: typeof DownloadRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AlternativesSlugRoute: typeof AlternativesSlugRoute
  ApiOembedRoute: typeof ApiOembedRoute
  CompareSlugRoute: typeof CompareSlugRoute
  EmbedVideoIdRoute: typeof EmbedVideoIdRoute
  MdShareVideoIdRoute: typeof MdShareVideoIdRoute
  MdSplatRoute: typeof MdSplatRoute
  ShareVideoIdRoute: typeof ShareVideoIdRoute
  CompareIndexRoute: typeof CompareIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternatives/$slug': {
      id: '/alternatives/$slug'
      path: '/alternatives/$slug'
      fullPath: '/alternatives/$slug'
      preLoaderRoute: typeof AlternativesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oembed': {
      id: '/api/oembed'
      path: '/api/oembed'
      fullPath: '/api/oembed'
      preLoaderRoute: typeof ApiOembedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$videoId': {
      id: '/embed/$videoId'
      path: '/embed/$videoId'
      fullPath: '/embed/$videoId'
      preLoaderRoute: typeof EmbedVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/md-share/$videoId': {
      id: '/md-share/$videoId'
      path: '/md-share/$videoId'
      fullPath: '/md-share/$videoId'
      preLoaderRoute: typeof MdShareVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/md/$': {
      id: '/md/$'
      path: '/md/$'
      fullPath: '/md/$'
      preLoaderRoute: typeof MdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$videoId': {
      id: '/share/$videoId'
      path: '/share/$videoId'
      fullPath: '/share/$videoId'
      preLoaderRoute: typeof ShareVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/videos/$videoId/': {
      id: '/app/videos/$videoId/'
      path: '/videos/$videoId'
      fullPath: '/app/videos/$videoId/'
      preLoaderRoute: typeof AppVideosVideoIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/videos/$videoId/analytics': {
      id: '/app/videos/$videoId/analytics'
      path: '/videos/$videoId/analytics'
      fullPath: '/app/videos/$videoId/analytics'
      preLoaderRoute: typeof AppVideosVideoIdAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppVideosVideoIdAnalyticsRoute: typeof AppVideosVideoIdAnalyticsRoute
  AppVideosVideoIdIndexRoute: typeof AppVideosVideoIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppVideosVideoIdAnalyticsRoute: AppVideosVideoIdAnalyticsRoute,
  AppVideosVideoIdIndexRoute: AppVideosVideoIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  UsernameRoute: UsernameRoute,
  AgentsRoute: AgentsRoute,
  BetaRoute: BetaRoute,
  DownloadRoute: DownloadRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AlternativesSlugRoute: AlternativesSlugRoute,
  ApiOembedRoute: ApiOembedRoute,
  CompareSlugRoute: CompareSlugRoute,
  EmbedVideoIdRoute: EmbedVideoIdRoute,
  MdShareVideoIdRoute: MdShareVideoIdRoute,
  MdSplatRoute: MdSplatRoute,
  ShareVideoIdRoute: ShareVideoIdRoute,
  CompareIndexRoute: CompareIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
