/**
 * Swift `CodingKeys` per persisted type, in `encode(to:)` order. These are
 * the keys each type OWNS; anything else in a JSON object is an unknown key
 * and is preserved in `$extra` (see parse.ts / serialize.ts).
 */

export const CODABLE_COLOR_KEYS = ["red", "green", "blue", "opacity"] as const;
export const CODABLE_POINT_KEYS = ["x", "y"] as const;

export const EXPORT_SETTINGS_KEYS = [
  "format",
  "resolution",
  "fps",
  "quality",
  "customWidth",
  "customHeight",
  "collapseStaticSpans",
] as const;

/** ProjectSettings.encode(to:) order. */
export const PROJECT_SETTINGS_KEYS = [
  "backgroundType",
  "gradientStartColor",
  "gradientEndColor",
  "solidColor",
  "backgroundImagePath",
  "backgroundPadding",
  "videoPlacement",
  "videoCustomX",
  "videoCustomY",
  "cornerRadius",
  "windowCornerRadius",
  "frameShape",
  "shadowRadius",
  "shadowOpacity",
  "gradientAngle",
  "backgroundBlur",
  "backgroundBrightness",
  "backgroundSaturation",
  "backgroundTintColor",
  "backgroundTintOpacity",
  "backgroundVignette",
  "backgroundPixelate",
  "backgroundHalftone",
  "backgroundNoise",
  "backgroundContrast",
  "backgroundHue",
  "showCursor",
  "cursorStyle",
  "cursorScale",
  "autoHideCursor",
  "autoHideDelay",
  "smoothCursor",
  "smoothingFactor",
  "cursorTilt",
  "cursorStretch",
  "cursorDrag",
  "cursorWeight",
  "cursorFluidEnabled",
  "cursorTension",
  "cursorFriction",
  "cursorMass",
  "showClickRipple",
  "cursorLoopToStart",
  "cursorStopAtEnd",
  "clickSoundEnabled",
  "clickSoundVolume",
  "clickSoundStyle",
  "keySoundEnabled",
  "keySoundVolume",
  "keySoundStyle",
  "showKeystrokes",
  "keystrokeOverlaySize",
  "keystrokeOverlayPosition",
  "keystrokeOverlayAnimation",
  "keystrokeOverlayScopeToRecordedApp",
  "clickRippleColor",
  "clickRippleSize",
  "showCamera",
  "cameraPosition",
  "cameraCustomX",
  "cameraCustomY",
  "cameraSize",
  "cameraShape",
  "cameraOrientation",
  "cameraMirrored",
  "cameraBrightness",
  "cameraContrast",
  "cameraSaturation",
  "cameraHue",
  "cameraFilter",
  "cameraRingLight",
  "cameraCornerRadius",
  "cameraBorderWidth",
  "cameraBorderColor",
  "cameraOpacity",
  "cameraTiltPitch",
  "cameraTiltYaw",
  "cameraTagText",
  "cameraTagSubtext",
  "cameraTagFontName",
  "cameraTagTextColor",
  "cameraTagBackgroundColor",
  "cameraTagPosition",
  "showDeviceFrame",
  "showWatermark",
  "watermarkFileName",
  "watermarkX",
  "watermarkY",
  "watermarkSize",
  "watermarkOpacity",
  "menuBarReplacement",
  "menuBarTitle",
  "menuBarTitleAlignment",
  "menuBarShowStatusIcons",
  "menuBarClock",
  "menuBarHeight",
  "systemAudioVolume",
  "microphoneVolume",
  "voiceOverVolume",
  "animationSpeed",
  "motionBlur",
  "motionBlurStrength",
  "parallaxStrength",
  "autoZoomLevel",
  "introSlideStyle",
  "introSlideDuration",
  "introSlideStart",
  "introSlideBounce",
  "introSlideSpeed",
  "introSlideDepth",
  "curtainUnveilCorner",
  "curtainUnveilDuration",
  "curtainUnveilStart",
  "curtainLogoFileName",
  "curtainLogoOpacity",
  "curtainLogoScale",
  "curtainLogoTint",
  "curtainColor",
  "cameraFollowSpeed",
  "screenTiltMode",
  "screenTiltAngle",
  "screenTiltYaw",
  "screenTiltRoll",
  "showSubtitles",
  "subtitleFontSize",
  "subtitlePosition",
  "subtitleStyle",
  "subtitleCustomX",
  "subtitleCustomY",
  "subtitleWeight",
  "subtitleUppercase",
  "subtitleFontName",
  "subtitleColor",
  "subtitleBackgroundColor",
  "highlightWords",
  "subtitleHighlightColor",
  "aspectRatio",
  "muteRecordedAudio",
  "exportSettings",
] as const;

/** Keys ProjectSettings writes with `encodeIfPresent` (omitted when nil). */
export const PROJECT_SETTINGS_OPTIONAL_KEYS = new Set<string>([
  "videoCustomX",
  "videoCustomY",
  "gradientAngle",
  "cameraCustomX",
  "cameraCustomY",
  "cameraBorderColor",
  "cameraTagFontName",
  "watermarkFileName",
  "curtainLogoFileName",
  "curtainLogoTint",
  "curtainColor",
  "subtitleCustomX",
  "subtitleCustomY",
  "subtitleFontName",
]);

export const ZOOM_REGION_KEYS = [
  "id",
  "startTime",
  "endTime",
  "zoomLevel",
  "focalPoint",
  "animationStyle",
  "cardOffsetX",
  "cardOffsetY",
  "followsCursor",
  "isAuto",
] as const;

export const TILT_REGION_KEYS = ["id", "startTime", "endTime", "pitch", "yaw", "roll", "animationStyle"] as const;

export const BLUR_REGION_KEYS = [
  "id",
  "startTime",
  "endTime",
  "label",
  "intensity",
  "style",
  "animated",
  "rectX",
  "rectY",
  "rectW",
  "rectH",
] as const;

export const HIGHLIGHT_REGION_KEYS = [
  "id",
  "startTime",
  "endTime",
  "label",
  "opacity",
  "rectX",
  "rectY",
  "rectW",
  "rectH",
] as const;

export const FOCUS_REGION_KEYS = [
  "id",
  "startTime",
  "endTime",
  "label",
  "intensity",
  "falloff",
  "style",
  "angle",
  "cornerRadius",
  "rectX",
  "rectY",
  "rectW",
  "rectH",
] as const;

export const CAMERA_LAYOUT_REGION_KEYS = ["id", "startTime", "endTime", "mode"] as const;

export const ANNOTATION_KEYS = [
  "id",
  "type",
  "startTime",
  "endTime",
  "x",
  "y",
  "arrowEndX",
  "arrowEndY",
  "text",
  "fontSize",
  "showBackground",
  "color",
  "backgroundColor",
  "lineWidth",
  "drawingStrokes",
  "fontWeight",
  "uppercase",
  "fontName",
  "opacity",
  "cornerRadius",
  "animatesIn",
  "showShadow",
  "enterEffect",
  "exitEffect",
  "backdropOpacity",
] as const;

export const VOICE_OVER_CLIP_KEYS = [
  "id",
  "fileName",
  "startTime",
  "sourceStartTime",
  "duration",
  "sourceDuration",
  "gain",
  "label",
] as const;

export const WORD_TIMING_KEYS = ["id", "startTime", "endTime", "text"] as const;
export const SUBTITLE_SEGMENT_KEYS = ["id", "startTime", "endTime", "text", "words"] as const;
export const SPEED_REGION_KEYS = ["id", "startTime", "endTime", "speed"] as const;
export const VIDEO_CLIP_SEGMENT_KEYS = ["id", "startTime", "endTime"] as const;
export const SOURCE_SEGMENT_KEYS = [
  "startTime",
  "duration",
  "kind",
  "contentX",
  "contentY",
  "contentWidth",
  "contentHeight",
] as const;

/** Project.encode(to:) order. */
export const PROJECT_KEYS = [
  "id",
  "name",
  "createdAt",
  "videoURL",
  "cursorDataURL",
  "keystrokeDataURL",
  "cameraVideoURL",
  "cameraTimeOffset",
  "settings",
  "zoomRegions",
  "tiltRegions",
  "blurRegions",
  "highlightRegions",
  "focusRegions",
  "cameraLayoutRegions",
  "annotations",
  "voiceOverClips",
  "subtitles",
  "speedRegions",
  "splitPoints",
  "videoClipSegments",
  "duration",
  "trimStart",
  "trimEnd",
  "recordingSourceKind",
  "recordedAppBundleID",
  "sourceSegments",
  "reminderDate",
  "isStillCapture",
  "stillTreatment",
] as const;
