import Foundation

/// How a zoom block animates in and out. Raw values are persistence identity.
///
/// Each style is a (response, damping) pair for the shared zoom spring:
/// `omegaMultiplier` scales the spring frequency (higher = faster), `damping`
/// is the zeta (below 1 overshoots, at/above 1 glides without bounce). The
/// same numbers drive the preview model and the exporter's camera path.
enum ZoomAnimationStyle: String, CaseIterable, Codable, Sendable {
    /// A near-cut: the zoom lands in ~0.2s — Screen Studio's "Instant Zoom".
    case instant = "Instant"
    case snappy = "Snappy"
    case smooth = "Smooth"
    case slowGlide = "Slow Glide"
    case cinematic = "Cinematic"

    var omegaMultiplier: Double {
        switch self {
        case .instant: return 8.0
        case .snappy: return 1.5
        case .smooth: return 1.0
        // The slow styles must still SETTLE — a spring that needs 4+ seconds
        // to land leaves short clips ending mid-zoom (tested against a 6s
        // clip: 0.38 never returned before the tail).
        case .slowGlide: return 0.75
        case .cinematic: return 0.6
        }
    }

    var damping: Double {
        switch self {
        case .instant: return 1.0
        case .snappy: return 0.72
        case .smooth: return 0.88
        case .slowGlide: return 1.0
        case .cinematic: return 1.05
        }
    }
}

struct ZoomRegion: Identifiable, Codable, Sendable {
    let id: UUID
    var startTime: TimeInterval
    var endTime: TimeInterval
    var zoomLevel: Double
    var focalPoint: CGPoint
    /// Per-block animation style; nil = the project's animationSpeed default
    /// (synthesized Codable: absent in old projects decodes as nil).
    var animationStyle: ZoomAnimationStyle?
    /// Card position excursion during the block, as canvas fractions
    /// (±ZoomFocalMath.cardOffsetLimit, Y-down — fully off-canvas allowed).
    /// The card slides here on the block's spring and
    /// returns home with the ramp-out — the "card low at an angle during the
    /// effect, centred after" composition. nil = no offset.
    var cardOffsetX: Double?
    var cardOffsetY: Double?
    /// nil/true = the camera blends toward the cursor while zoomed (the
    /// default). false = FIXED focus: the block aims exactly where its focal
    /// point says — set automatically when the user drags the on-canvas
    /// focal target, so aiming the shot isn't fought by cursor-follow.
    var followsCursor: Bool?
    /// true = this region was generated by Auto Zoom. Regenerating auto zooms
    /// replaces only these; user-placed regions (nil/false) are never touched.
    /// Synthesized Codable: absent in old projects decodes as nil.
    var isAuto: Bool?

    var duration: TimeInterval { endTime - startTime }

    init(
        id: UUID = UUID(),
        startTime: TimeInterval,
        endTime: TimeInterval,
        zoomLevel: Double = 2.0,
        focalPoint: CGPoint = CGPoint(x: 0.5, y: 0.5),
        animationStyle: ZoomAnimationStyle? = nil,
        cardOffsetX: Double? = nil,
        cardOffsetY: Double? = nil,
        followsCursor: Bool? = nil,
        isAuto: Bool? = nil
    ) {
        self.id = id
        self.startTime = startTime
        self.endTime = endTime
        self.zoomLevel = zoomLevel
        self.focalPoint = focalPoint
        self.animationStyle = animationStyle
        self.cardOffsetX = cardOffsetX
        self.cardOffsetY = cardOffsetY
        self.followsCursor = followsCursor
        self.isAuto = isAuto
    }
}
